name: activity_list

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 1/3 * *'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install
        run: |
          rm yarn.lock
          yarn install
      - name: Run
        env:
          KEY: ${{ secrets.KEY }}
          IV: ${{ secrets.IV }}
        run: |
          yarn start
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'update'
          branch: activity
          commit_options: '--no-verify --signoff'
          file_pattern: data/**
          push_options: '--force'
          commit_user_name: 'KudouRan'
          commit_user_email: 'Kudou.Ran@outlook.com'
          skip_fetch: true
          skip_checkout: false
          create_branch: true
      - name: Push to Gitee
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gitee.com >> ~/.ssh/known_hosts
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          git remote set-url --push origin ${{ secrets.GITEE_REPO }}
          GIT_BRANCH="activity"
          git push origin "$GIT_BRANCH":"$GIT_BRANCH" --force
